### PR TITLE
S16 code uml

### PR DESCRIPTION
**Pull request by ebramsherif**
Still missing locales + docs + UML + test
@markmorcos @mohamed-mehany Review the code
@sharkawy94 Please review the scenario

### CODE REVIEW

**Comment by ebramsherif** [comment]
@potatoh check what?

**Comment by potatoh** [comment]
As in checked😂

**Comment by ebramsherif** [comment]
Okay so please place a Documentation Reviewed label on both issues of S13 and S16 and remove their documentation pending labels

**Comment by potatoh** [comment]
Done

**Comment by narimanhesham** [comment]
@ebramsherif 
All your test cases pass so you are done

**Pull request merged**
