### PR TITLE
S13 Code + UML

### PR DESCRIPTION
**Pull request by ebramsherif**
@mohamed-mehany @markmorcos Please review the code
@mokhtar93 Please review the UML
@narimanhesham Please run the test
@potatoh Please review documentation in FindingPost Controller
@sharkawy94 Please review the scenario

Issue: #36

### CODE REVIEW

**Comment by ebramsherif** [comment]
@potatoh It's there, I added docs for auth minutes ago aswell.Haters gonna hate, potatoes gonna potate.

**Comment by ebramsherif** [comment]
@markmorcos @mohamed-mehany fixed the test we talked about.
Also fixed function mine under the controller.

**Comment by potatoh** [comment]
Potato approves

**Comment by ebramsherif** [comment]
Done

**Comment by narimanhesham** [comment]
@ebramsherif 
Test case 2,3 and 4 fails so please fix them and tag me when you finish

**Comment by narimanhesham** [comment]
@ebramsherif 
Your test cases pass but they don't cover the if part in method unique_report in finding_post_report.rb model, as you said you aren't using this method anymore in sprint1 I won't be asking you to cover it in this sprint.

**Comment by narimanhesham** [comment]
@ebramsherif 
All the test cases pass, so you are done

**Pull request merged**
