### PR TITLE
S24

### PR DESCRIPTION
**Pull request by markmorcos**

### CODE REVIEW

**Comment by mohamed-mehany** [comment]
@markmorcos same comment as S28, please either remove the commented code from the following files or use it
Mafqood/app/models/missing_post.rb
Mafqood/app/models/missing_post_report.rb 
Mafqood/app/models/finding_post.rb 
Mafqood/app/controllers/finding_posts_controller.rb
Mafqood/app/controllers/users_controller.rb 
Mafqood/app/controllers/missing_posts_controller.rb
Mafqood/app/controllers/application_controller.rb
Mafqood/app/admin/location.rb

**Comment by narimanhesham** [comment]
@markmorcos Are the tests ready for reviewing or not ?

**Comment by markmorcos** [comment]
@narimanhesham I have not done any tests since I haven't modified controllers and all my work was based on the active admin gem and named scopes only.

**Comment by narimanhesham** [comment]
@markmorcos what about the models, Did you add or modify anything in them ?

**Comment by markmorcos** [comment]
@narimanhesham please review tests

**Comment by markmorcos** [comment]
@mokhtar93 please review UML

**Pull request merged**
