### PR TITLE
Implemented changing languages from/to English/Arabic and ability to vie...

### PR DESCRIPTION
**Pull request by markmorcos**
...w own posts
@mohamed-mehany please review code
#34 #35

### CODE REVIEW

**Comment by markmorcos** [comment]
@mokhtar93 please review UMLs
@sharkawy94 please review scenario

**Comment by markmorcos** [comment]
@potatoh please review documentation

**Comment by markmorcos** [comment]
@narimanhesham please review specs

**Comment by potatoh** [comment]
@markmorcos

**Comment by ebramsherif** [comment]
Scenario approved

However please read the following comments (written as a team member not a reviewer)
- @mohamed-mehany Posts.haml file will will cause problems with future merges as now finding posts have their own javascript file, as well as missing and suspect as of sprint 1.
- Please review/discard changes to finding & missing posts as they are only renaming (which I've done because mark has reopened my previous issue and its commited on my branches). The files have been modified drastically since sprint 1 and mark's copy is only as of sprint 0 so it might cause lots of conflicts

**Comment by ebramsherif** [comment]
@potatoh The branch/issue were never closed so there is no point for the reopen label.

**Comment by ebramsherif** [comment]
@markmorcos @mohamed-mehany Discard my previous comment about the post file, I didn't realize mark has done both stories on a single branch.

**Comment by markmorcos** [comment]
@mokhtar93 please check fixed UMLs

**Pull request merged**
